plugins { id "com.android.application" }

android {
    namespace "com.shyam026.buddyassistant"
    compileSdk 35

    defaultConfig {
        applicationId "com.shyam026.buddyassistant"
        minSdk 23
        targetSdk 35
        versionCode 10
        versionName "3.5-GeminiSettings"
    }

    testOptions { unitTests.returnDefaultValues = true }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    testImplementation "junit:junit:4.13.2"
}
